workflows:

  web:
    name: Web
    max_build_duration: 30
    environment:
      flutter: default
      groups:
        - Firebase
    scripts:
      - flutter build web --release
      - echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
      - firebase deploy --only hosting
 